name: "SSH Primary"
description: "Serveur SSH principal avec support SFTP, clé publique et mot de passe"
version: "1.0.7"
slug: "ssh_primary"
url: "https://github.com/tgillier/addons-homeassistant"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false

ports:
  22/tcp: 22222
ports_description:
  22/tcp: "Port SSH principal"

# Accès aux dossiers Home Assistant
map:
  - type: config
    read_only: false
  - type: data
    read_only: false
  - type: share
    read_only: false
  - type: ssl
    read_only: true
  - type: backup
    read_only: false
  - type: media
    read_only: false
  - type: addons
    read_only: true

options:
  username: "root"
  authorized_keys: []
  password: ""
  auth_mode: "key_or_password"
  sftp_enabled: true
  sftp_only: false
  log_level: "INFO"
  banner: ""

schema:
  username: str
  authorized_keys:
    - str
  password: password
  auth_mode: "list(key_only|password_only|key_or_password)"
  sftp_enabled: bool
  sftp_only: bool
  log_level: "list(DEBUG|INFO|WARNING|ERROR)"
  banner: str

stage: stable
