name: "Chrome"
description: "Chrome via linuxserver"
version: "0.1.0"
slug: "chrome_local"
init: false
arch:
  - amd64
  - aarch64

startup: services
boot: auto

ports:
  3001/tcp: 3001

options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Paris"
  LC_ALL: "fr_FR.UTF-8"

schema:
  PUID: int
  PGID: int
  TZ: str
  LC_ALL: str
  CONFIG_PATH: str
