name: "Chrome"
version: "0.1.0"
slug: "chrome_local"
description: "Chrome via linuxserver/selkies"
arch:
  - amd64
startup: services
boot: auto
image: "lscr.io/linuxserver/chrome:latest"

options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Paris"
  LC_ALL: "fr_FR.UTF-8"
  SHM_SIZE: "1gb"
  CONFIG_PATH: "/home/tgillier/chrome/config"

schema:
  PUID: int
  PGID: int
  TZ: str
  LC_ALL: str
  SHM_SIZE: str
  CONFIG_PATH: str

ports:
  3001/tcp: 3001

map:
  - config:rw
  - share:rw