name: "Portainer Edge Agent"
description: >-
  Agent Edge Portainer (Standard) — Se connecte à un serveur Portainer distant
  pour gérer cet environnement Docker depuis une instance centralisée.
version: "1.0.2"
slug: "portainer_agent"
url: "https://www.portainer.io/"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
docker_api: true
map:
  - type: data
    read_only: false
options:
  edge_key: ""
  edge_id: ""
  edge_insecure_poll: false
  log_level: "INFO"
schema:
  edge_key: str
  edge_id: str
  edge_insecure_poll: bool
  log_level: "list(DEBUG|INFO|WARN|ERROR)"
stage: stable
